/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Estudio;
import classes.Filme;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static telas.CadastroEstudio.listaEstudios;

/**
 *
 * @author haris
 */
public class addEstudio extends javax.swing.JFrame {

    private ArrayList<Estudio> estudios;
    private Filme filme;
    String botao = "";

    /**
     * Creates new form addEstudio
     */
    public addEstudio(Filme filme, ArrayList<Estudio> listaEstudio) {
        initComponents();

        botoesDefault();

        this.filme = filme;
        this.estudios = listaEstudio;
        carregaTabelaEstudios();
    }

    private void carregaTabelaEstudios() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Nome", "ID do Estudio"}, 0);
        for (Estudio e : this.filme.getEstudios()) {
            Object[] linha = {e.getNome(), e.getIdestudio()};
            modelo.addRow(linha);
        }
        tblEstudios.setModel(modelo);
    }

    private Estudio verificaEstudio() {
        for (int i = 0; i < estudios.size(); i++) {
            if (estudios.get(i).getIdestudio().equals(txtIdEstudio.getText())) {
                return (estudios.get(i));
            }
        }return null;
    }

    private void criaEstudio() {
        if (!validaCampos()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "erro", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        Estudio e = verificaEstudio();
        if(e == null){
            JOptionPane.showMessageDialog(null, "Estudio não existe!", "erro", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        if(filme.addEstudio(e)){
            JOptionPane.showMessageDialog(null, "Estúdio adicionado com sucesso!", "erro", JOptionPane.PLAIN_MESSAGE);
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Estúdio já está cadastrado", "erro", JOptionPane.PLAIN_MESSAGE);
        }
    }

    private void excluiEstudio() {

        if (txtIdEstudio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o ID do Estúdio", "erro", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        Estudio e = verificaEstudio();
        if(e == null){
            JOptionPane.showMessageDialog(null, "Estudio não existe!", "erro", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        if(filme.removeEstudio(e.getIdestudio())){
            JOptionPane.showMessageDialog(null, "Estúdio adicionado com sucesso!", "erro", JOptionPane.PLAIN_MESSAGE);
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Estúdio já está cadastrado", "erro", JOptionPane.PLAIN_MESSAGE);
        }

    }

    private boolean validaCampos() {

        if (txtNomeEstudio.getText().equals("") || txtIdEstudio.getText().equals("")) {

            return false;
        }

        return true;
    }

    private void limpaConteudos() {
        txtNomeEstudio.setText("");
        txtIdEstudio.setText("");

    }

    private void botoesDefault() {
        btnAdicionarEstudio.setEnabled(true);
        btnRemoverEstudio.setEnabled(true);
        btnOk.setEnabled(false);

        //Inicializar os campos de texto
        txtNomeEstudio.setEnabled(false);
        txtIdEstudio.setEnabled(false);
    }

    private void botoesHabilitados() {
        btnAdicionarEstudio.setEnabled(false);
        btnRemoverEstudio.setEnabled(false);
        btnOk.setEnabled(true);

        //Inicializar os campos de texto
        txtNomeEstudio.setEnabled(true);
        txtIdEstudio.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudios = new javax.swing.JTable();
        btnRemoverEstudio = new javax.swing.JButton();
        btnAdicionarEstudio = new javax.swing.JToggleButton();
        txtIdEstudio = new javax.swing.JTextField();
        lblIdEstudio = new javax.swing.JLabel();
        lblNomeEstudio = new javax.swing.JLabel();
        txtNomeEstudio = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar e Remover Estúdio");

        jPanel1.setBackground(new java.awt.Color(114, 134, 211));

        tblEstudios.setBackground(new java.awt.Color(229, 224, 255));
        tblEstudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "ID Estúdio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEstudios);
        if (tblEstudios.getColumnModel().getColumnCount() > 0) {
            tblEstudios.getColumnModel().getColumn(0).setResizable(false);
            tblEstudios.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblEstudios.getColumnModel().getColumn(1).setResizable(false);
            tblEstudios.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        btnRemoverEstudio.setBackground(new java.awt.Color(142, 167, 233));
        btnRemoverEstudio.setForeground(new java.awt.Color(255, 242, 242));
        btnRemoverEstudio.setText("Remover Estudio");
        btnRemoverEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEstudioActionPerformed(evt);
            }
        });

        btnAdicionarEstudio.setBackground(new java.awt.Color(142, 167, 233));
        btnAdicionarEstudio.setForeground(new java.awt.Color(255, 242, 242));
        btnAdicionarEstudio.setText("Adicionar Estudio");
        btnAdicionarEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEstudioActionPerformed(evt);
            }
        });

        lblIdEstudio.setForeground(new java.awt.Color(255, 242, 242));
        lblIdEstudio.setText("ID Estúdio:");

        lblNomeEstudio.setForeground(new java.awt.Color(255, 242, 242));
        lblNomeEstudio.setText("Nome Estúdio:");

        txtNomeEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEstudioActionPerformed(evt);
            }
        });

        btnOk.setBackground(new java.awt.Color(142, 167, 233));
        btnOk.setForeground(new java.awt.Color(255, 242, 242));
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(142, 167, 233));
        btnVoltar.setForeground(new java.awt.Color(255, 242, 242));
        btnVoltar.setText("voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnRemoverEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVoltar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarEstudio)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblNomeEstudio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNomeEstudio))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblIdEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIdEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEstudioActionPerformed

    private void btnRemoverEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEstudioActionPerformed
        botao = "re";
        botoesHabilitados();

    }//GEN-LAST:event_btnRemoverEstudioActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (botao.equals("ad")) {
            criaEstudio();
        } else if (botao.equals("re")) {
            excluiEstudio();
        }
        botao = "";
        carregaTabelaEstudios();
        limpaConteudos();
        botoesDefault();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAdicionarEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEstudioActionPerformed

        botao = "ad";
        botoesHabilitados();
    }//GEN-LAST:event_btnAdicionarEstudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new addEstudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdicionarEstudio;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRemoverEstudio;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdEstudio;
    private javax.swing.JLabel lblNomeEstudio;
    private javax.swing.JTable tblEstudios;
    private javax.swing.JTextField txtIdEstudio;
    private javax.swing.JTextField txtNomeEstudio;
    // End of variables declaration//GEN-END:variables
}
