/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.text.SimpleDateFormat;
import java.util.Date;
import classes.Ator;
import classes.BancoDeDados;
import classes.Diretor;
import classes.Funcionario;
import java.io.File;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author wesle
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {

    BancoDeDados bd;
    
    
    
    public TelaCadastroFuncionario() {
        initComponents();
        
       jtbEditar.setEnabled(false);
        
        File fileBd = new File(BancoDeDados.getFilePath());
        if(fileBd.exists()){
            bd = BancoDeDados.readBancoDeDados();
        }else{
            bd = new BancoDeDados();
            BancoDeDados.writeBancoDeDados(bd);
        }
        carregarTabelaFuncionario();
    }

    public void carregarTabelaFuncionario(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Nome", "CPF","Função", "Telefone","Email","Sexo","Nacionalidade","Percentual"}, 0);
        
        
        for(int i=0;i<bd.getFuncionarios().size();i++){
            
            String obj;
            String percentual = "";
            
            if(bd.getFuncionarios().get(i) instanceof Ator){
                obj = "Ator";
            }else{
                obj = "Diretor";
                percentual = Double.toString(((Diretor) bd.getFuncionarios().get(i)).getPercentual());
            }
            
            Object linha[] = new Object[] {bd.getFuncionarios().get(i).getNome(),bd.getFuncionarios().get(i).getCpf(),
            obj,bd.getFuncionarios().get(i).getTelefone(),
            bd.getFuncionarios().get(i).getEmail(),bd.getFuncionarios().get(i).getSexo(),
            bd.getFuncionarios().get(i).getNacionalidade(), percentual};
            
            modelo.addRow(linha);
            
        }
        
        tblFuncionario.setModel(modelo);
        
        tblFuncionario.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblFuncionario.getColumnModel().getColumn(1).setPreferredWidth(5);
        tblFuncionario.getColumnModel().getColumn(2).setPreferredWidth(10);
        tblFuncionario.getColumnModel().getColumn(3).setPreferredWidth(10);
        tblFuncionario.getColumnModel().getColumn(4).setPreferredWidth(10);
        tblFuncionario.getColumnModel().getColumn(5).setPreferredWidth(15);
        tblFuncionario.getColumnModel().getColumn(6).setPreferredWidth(15);
        tblFuncionario.getColumnModel().getColumn(7).setPreferredWidth(15);
    }
    
    public boolean cpfValido(String Cpf){
        boolean count = true;
        if (Cpf.equals("0")){
            count = false;
        } else {
            for (int i = 0; i < Cpf.length(); i++){
                    if(Cpf.charAt(i) != '0' && Cpf.charAt(i) != '1' && Cpf.charAt(i) != '2' && Cpf.charAt(i) != '3' && Cpf.charAt(i) != '4' 
                        && Cpf.charAt(i) != '5'&& Cpf.charAt(i) != '6' && Cpf.charAt(i) != '7' && Cpf.charAt(i) != '8' && Cpf.charAt(i) != '9'){
                        count = false;
                    }
                }
        }
        
        for(int i = 0; i < bd.getFuncionarios().size(); i++){
            if(bd.getFuncionarios().get(i).getCpf().equals(Cpf)){
                count = false;
            }
        }
        
        return count;

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlbComando = new javax.swing.JLabel();
        jlbTipoConta = new javax.swing.JLabel();
        jrbDiretor = new javax.swing.JRadioButton();
        jrbAtor = new javax.swing.JRadioButton();
        jlbNome = new javax.swing.JLabel();
        jtxNome = new javax.swing.JTextField();
        jlbCpf = new javax.swing.JLabel();
        jlbTelefone = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbData_nascimento = new javax.swing.JLabel();
        jlbSexo = new javax.swing.JLabel();
        jlbNacionalidade = new javax.swing.JLabel();
        jtxCpf = new javax.swing.JTextField();
        jtxTelefone = new javax.swing.JTextField();
        jtxEmail = new javax.swing.JTextField();
        jtxSexo = new javax.swing.JTextField();
        jtxNacionalidade = new javax.swing.JTextField();
        jtxData_nascimento = new javax.swing.JTextField();
        jlbPercentual = new javax.swing.JLabel();
        jtxPercentual = new javax.swing.JTextField();
        jtxExperiencia = new javax.swing.JTextField();
        jlbExperiencia = new javax.swing.JLabel();
        jtxBiografia = new javax.swing.JTextField();
        jlbBiografia = new javax.swing.JLabel();
        jlbSenha = new javax.swing.JLabel();
        jpwSenha = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jtbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtbSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jtbEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Funcionário");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(114, 134, 211));

        jPanel2.setBackground(new java.awt.Color(114, 134, 211));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Cadastro de funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 242, 242))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 242, 242));

        jlbComando.setForeground(new java.awt.Color(255, 242, 242));
        jlbComando.setText("Preencha corretamente todos os campos a seguir:");

        jlbTipoConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbTipoConta.setForeground(new java.awt.Color(255, 242, 242));
        jlbTipoConta.setText("Tipo de funcionario:");

        jrbDiretor.setForeground(new java.awt.Color(255, 242, 242));
        jrbDiretor.setText("Diretor");
        jrbDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDiretorActionPerformed(evt);
            }
        });

        jrbAtor.setForeground(new java.awt.Color(255, 242, 242));
        jrbAtor.setText("Ator");
        jrbAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAtorActionPerformed(evt);
            }
        });

        jlbNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbNome.setForeground(new java.awt.Color(255, 242, 242));
        jlbNome.setText("Nome:");

        jtxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNomeActionPerformed(evt);
            }
        });

        jlbCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbCpf.setForeground(new java.awt.Color(255, 242, 242));
        jlbCpf.setText("CPF:");

        jlbTelefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbTelefone.setForeground(new java.awt.Color(255, 242, 242));
        jlbTelefone.setText("Telefone:");

        jlbEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbEmail.setForeground(new java.awt.Color(255, 242, 242));
        jlbEmail.setText("Email:");

        jlbData_nascimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbData_nascimento.setForeground(new java.awt.Color(255, 242, 242));
        jlbData_nascimento.setText("Data de Nascimento:");

        jlbSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbSexo.setForeground(new java.awt.Color(255, 242, 242));
        jlbSexo.setText("Sexo:");

        jlbNacionalidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbNacionalidade.setForeground(new java.awt.Color(255, 242, 242));
        jlbNacionalidade.setText("Nacionalidade:");

        jtxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCpfActionPerformed(evt);
            }
        });

        jtxTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxTelefoneActionPerformed(evt);
            }
        });

        jtxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxSexoActionPerformed(evt);
            }
        });

        jtxNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNacionalidadeActionPerformed(evt);
            }
        });

        jlbPercentual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbPercentual.setForeground(new java.awt.Color(255, 242, 242));
        jlbPercentual.setText("Percentual:");

        jtxExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxExperienciaActionPerformed(evt);
            }
        });

        jlbExperiencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbExperiencia.setForeground(new java.awt.Color(255, 242, 242));
        jlbExperiencia.setText("Tempo de Experiência:");

        jlbBiografia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbBiografia.setForeground(new java.awt.Color(255, 242, 242));
        jlbBiografia.setText("Biografia:");

        jlbSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbSenha.setForeground(new java.awt.Color(255, 242, 242));
        jlbSenha.setText("Senha:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbExperiencia)
                        .addGap(6, 6, 6)
                        .addComponent(jtxExperiencia))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNome)
                            .addComponent(jlbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbTelefone)
                            .addComponent(jlbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbData_nascimento)
                            .addComponent(jlbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNacionalidade)
                            .addComponent(jlbPercentual))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpwSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxData_nascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxNacionalidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxPercentual)
                            .addComponent(jtxNome)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbBiografia)
                        .addGap(18, 18, 18)
                        .addComponent(jtxBiografia))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbTipoConta)
                                .addGap(18, 18, 18)
                                .addComponent(jrbDiretor)
                                .addGap(45, 45, 45)
                                .addComponent(jrbAtor))
                            .addComponent(jlbComando))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 36, Short.MAX_VALUE)
                .addComponent(jlbComando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoConta)
                    .addComponent(jrbDiretor)
                    .addComponent(jrbAtor))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCpf)
                    .addComponent(jtxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSenha)
                    .addComponent(jpwSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTelefone)
                    .addComponent(jtxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmail)
                    .addComponent(jtxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbData_nascimento)
                    .addComponent(jtxData_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSexo))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNacionalidade)
                    .addComponent(jtxNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbExperiencia))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbBiografia)
                    .addComponent(jtxBiografia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jPanel3.setBackground(new java.awt.Color(114, 134, 211));

        jtbCancelar.setBackground(new java.awt.Color(142, 167, 233));
        jtbCancelar.setForeground(new java.awt.Color(255, 242, 242));
        jtbCancelar.setText("Cancelar");
        jtbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download-removebg-preview.png"))); // NOI18N

        jtbSalvar.setBackground(new java.awt.Color(142, 167, 233));
        jtbSalvar.setForeground(new java.awt.Color(255, 242, 242));
        jtbSalvar.setText("Salvar");
        jtbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbSalvarActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tblFuncionario.setBackground(new java.awt.Color(229, 224, 255));
        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Senha", "Telefone", "Email", "Sexo", "Nacionalidade", "Pagamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFuncionario);

        jtbEditar.setBackground(new java.awt.Color(142, 167, 233));
        jtbEditar.setForeground(new java.awt.Color(255, 242, 242));
        jtbEditar.setText("Editar");
        jtbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jtbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(jtbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jtbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDiretorActionPerformed
      jrbAtor.setSelected(false);
        
      jlbCpf.setEnabled(true);
      jlbData_nascimento.setEnabled(true);
      jlbExperiencia.setEnabled(false);
      jlbBiografia.setEnabled(false);
      jlbPercentual.setEnabled(true);
        
      jtxCpf.setEnabled(true);
      jtxData_nascimento.setEnabled(true);
      jtxExperiencia.setEnabled(false);
      jtxBiografia.setEnabled(false);
      jtxPercentual.setEnabled(true);
      
        

    }//GEN-LAST:event_jrbDiretorActionPerformed

    private void jrbAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAtorActionPerformed
      jrbDiretor.setSelected(false);
        
      jlbCpf.setEnabled(true);
      jlbData_nascimento.setEnabled(true);
      jlbExperiencia.setEnabled(true);
      jlbBiografia.setEnabled(true);
      jlbPercentual.setEnabled(false);
       
      jtxCpf.setEnabled(true);
      jtxData_nascimento.setEnabled(true);
      jtxExperiencia.setEnabled(true);
      jtxBiografia.setEnabled(true);
      jtxPercentual.setEnabled(false);
        

    }//GEN-LAST:event_jrbAtorActionPerformed

    private void jtxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNomeActionPerformed
        JOptionPane.showMessageDialog(null, "Preencha todos os campos disponíveis para continuar!", "Aviso!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jtxNomeActionPerformed

    private void jtxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCpfActionPerformed

    private void jtxTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxTelefoneActionPerformed

    private void jtxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxSexoActionPerformed

    private void jtxNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNacionalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxNacionalidadeActionPerformed

    private void jtxExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxExperienciaActionPerformed

    private void jtbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jtbCancelarActionPerformed

    private void jtbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbSalvarActionPerformed
        //ATOR
        if(jrbAtor.isSelected()){
            if (jtxNome.getText().equals("") || jtxCpf.getText().equals("") 
                    || jtxTelefone.getText().equals("") || jtxEmail.getText().equals("") 
                    || jtxSexo.getText().equals("") || jtxData_nascimento.getText().equals("") 
                    || jtxNacionalidade.getText().equals("") 
                    || jtxBiografia.getText().equals("") || jtxExperiencia.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos disponíveis para continuar!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            } else if(cpfValido(jtxCpf.getText()) == false){
                JOptionPane.showMessageDialog(null, "Cpf inválido!", "Aviso!", JOptionPane.WARNING_MESSAGE);   
            } else{
                Date date;
                SimpleDateFormat DateFor = new SimpleDateFormat("dd/MM/yyyy");
                try{
                    Date dates = DateFor.parse(jtxData_nascimento.getText());
                    Ator novoAtor = new Ator(Integer.parseInt(jtxExperiencia.getText()),jtxBiografia.getText(),jtxCpf.getText(),
                        jtxNome.getText(), jpwSenha.getText(),jtxEmail.getText(),jtxTelefone.getText(),dates,jtxSexo.getText(),
                        jtxNacionalidade.getText());
                    bd.getFuncionarios().add(novoAtor);
                    BancoDeDados.writeBancoDeDados(bd);
                    
                    JOptionPane.showMessageDialog(null, "Ator Cadastrado com sucesso!", "Aviso!", JOptionPane.WARNING_MESSAGE);
                         
                }catch (ParseException e) {e.printStackTrace();}

            }
        } 
        //DIRETOR
        else if(jrbDiretor.isSelected()){
            if (jtxNome.getText().equals("") | jtxCpf.getText().equals("") 
                    | jtxTelefone.getText().equals("") | jtxEmail.getText().equals("") 
                    | jtxSexo.getText().equals("") | jtxData_nascimento.getText().equals("") 
                    | jtxNacionalidade.getText().equals("") |  jtxPercentual.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos disponíveis para continuar!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            } else if(cpfValido(jtxCpf.getText()) == false){
                JOptionPane.showMessageDialog(null, "Cpf inválido!", "Aviso!", JOptionPane.WARNING_MESSAGE);   
            } else{
                Date date;
                SimpleDateFormat DateFor = new SimpleDateFormat("dd/MM/yyyy");
                try{
                    Date dates = DateFor.parse(jtxData_nascimento.getText());
                    Diretor novoDiretor = new Diretor(Double.parseDouble(jtxPercentual.getText()),jtxCpf.getText(),
                        jtxNome.getText(),jpwSenha.getText(),jtxEmail.getText(),jtxTelefone.getText(),dates,jtxSexo.getText(),
                        jtxNacionalidade.getText());
                    bd.getFuncionarios().add(novoDiretor);
                    BancoDeDados.writeBancoDeDados(bd);
                    
                    JOptionPane.showMessageDialog(null, "Diretor Cadastrado com sucesso!", "Aviso!", JOptionPane.WARNING_MESSAGE);
                         
                }catch (ParseException e) {e.printStackTrace();}
                
            }
        }
        
        //carregar os dados da tabela
        carregarTabelaFuncionario();
        
        //limpar os campos
        jtxNome.setText("");
        jtxCpf.setText("");
        jpwSenha.setText("");
        jtxTelefone.setText("");
        jtxEmail.setText("");
        jtxData_nascimento.setText("");
        jtxSexo.setText("");
        jtxNacionalidade.setText("");
        
        jtxPercentual.setText("");
        jtxExperiencia.setText("");
        jtxBiografia.setText("");
    }//GEN-LAST:event_jtbSalvarActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        int i = tblFuncionario.getSelectedRow();
        
        if(i>=0 && i<bd.getFuncionarios().size()){
            Funcionario func = bd.getFuncionarios().get(i);
            
            SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");  
            String strDate = formatter.format(func.getData_nascimento());
            
            jtxNome.setText(func.getNome());
            jtxCpf.setText(func.getCpf());
            jtxTelefone.setText(func.getTelefone());
            jtxEmail.setText(func.getEmail());
            jtxData_nascimento.setText(strDate);
            jtxSexo.setText(func.getSexo());
            jtxNacionalidade.setText(func.getNacionalidade());
            
        }
        
        jlbCpf.setEnabled(false);
        jlbData_nascimento.setEnabled(false);
        
        jtxCpf.setEnabled(false);
        jtxData_nascimento.setEnabled(false);
        
        jtbEditar.setEnabled(true);
    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void jtbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbEditarActionPerformed
        int index = tblFuncionario.getSelectedRow();
        
        bd.getFuncionarios().get(index).setNome(jtxNome.getText());
        bd.getFuncionarios().get(index).setSenha(jpwSenha.getText());
        bd.getFuncionarios().get(index).setTelefone(jtxTelefone.getText());
        bd.getFuncionarios().get(index).setEmail(jtxEmail.getText());
        bd.getFuncionarios().get(index).setSexo(jtxSexo.getText());
        bd.getFuncionarios().get(index).setNacionalidade(jtxNacionalidade.getText());
        
        
        JOptionPane.showMessageDialog(null, "Dados editados com sucesso!", "Aviso!", JOptionPane.WARNING_MESSAGE);
        
        //salvar no banco de dados
        BancoDeDados.writeBancoDeDados(bd);
     
        //carregar os dados da tabela
        carregarTabelaFuncionario();
        
        jlbCpf.setEnabled(true);
        jlbData_nascimento.setEnabled(true);
        
        jtxCpf.setEnabled(true);
        jtxData_nascimento.setEnabled(true);

        //limpar os campos
        jtxNome.setText("");
        jtxCpf.setText("");
        jpwSenha.setText("");
        jtxTelefone.setText("");
        jtxEmail.setText("");
        jtxData_nascimento.setText("");
        jtxSexo.setText("");
        jtxNacionalidade.setText("");
        
        jtxPercentual.setText("");
        jtxExperiencia.setText("");
        jtxBiografia.setText("");
    }//GEN-LAST:event_jtbEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbBiografia;
    private javax.swing.JLabel jlbComando;
    private javax.swing.JLabel jlbCpf;
    private javax.swing.JLabel jlbData_nascimento;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbExperiencia;
    private javax.swing.JLabel jlbNacionalidade;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbPercentual;
    private javax.swing.JLabel jlbSenha;
    private javax.swing.JLabel jlbSexo;
    private javax.swing.JLabel jlbTelefone;
    private javax.swing.JLabel jlbTipoConta;
    private javax.swing.JPasswordField jpwSenha;
    private javax.swing.JRadioButton jrbAtor;
    private javax.swing.JRadioButton jrbDiretor;
    private javax.swing.JButton jtbCancelar;
    private javax.swing.JButton jtbEditar;
    private javax.swing.JButton jtbSalvar;
    private javax.swing.JTextField jtxBiografia;
    private javax.swing.JTextField jtxCpf;
    private javax.swing.JTextField jtxData_nascimento;
    private javax.swing.JTextField jtxEmail;
    private javax.swing.JTextField jtxExperiencia;
    private javax.swing.JTextField jtxNacionalidade;
    private javax.swing.JTextField jtxNome;
    private javax.swing.JTextField jtxPercentual;
    private javax.swing.JTextField jtxSexo;
    private javax.swing.JTextField jtxTelefone;
    private javax.swing.JTable tblFuncionario;
    // End of variables declaration//GEN-END:variables
}
