/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Ator;
import classes.BancoDeDados;
import classes.Diretor;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author wesle
 */
public class TelaLogin extends javax.swing.JFrame {

    BancoDeDados bd;

    public TelaLogin() {
        initComponents();

        File fileBd = new File(BancoDeDados.getFilePath());
        if (fileBd.exists()) {
            bd = BancoDeDados.readBancoDeDados();
        } else {
            bd = new BancoDeDados();
            BancoDeDados.writeBancoDeDados(bd);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosLogin = new javax.swing.JPanel();
        jlbComando = new javax.swing.JLabel();
        jlbCPF = new javax.swing.JLabel();
        jtxCPF = new javax.swing.JTextField();
        jlbSenha = new javax.swing.JLabel();
        jbtLogin = new javax.swing.JButton();
        jpwSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone.png")).getImage());

        pnlDadosLogin.setBackground(new java.awt.Color(114, 134, 211));
        pnlDadosLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dados para login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 242, 242))); // NOI18N

        jlbComando.setForeground(new java.awt.Color(255, 242, 242));
        jlbComando.setText("Preencha corretamente todos os dados a seguir:");

        jlbCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbCPF.setForeground(new java.awt.Color(255, 242, 242));
        jlbCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/round-account-button-with-user-inside_icon-icons.com_72596.png"))); // NOI18N
        jlbCPF.setText("CPF:");

        jlbSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbSenha.setForeground(new java.awt.Color(255, 242, 242));
        jlbSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/password_icon_183875 (1).png"))); // NOI18N
        jlbSenha.setText("Senha:");

        jbtLogin.setBackground(new java.awt.Color(142, 167, 233));
        jbtLogin.setForeground(new java.awt.Color(255, 242, 242));
        jbtLogin.setText("Login");
        jbtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoginActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/istockphoto-1193108274-612x612__1_-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pnlDadosLoginLayout = new javax.swing.GroupLayout(pnlDadosLogin);
        pnlDadosLogin.setLayout(pnlDadosLoginLayout);
        pnlDadosLoginLayout.setHorizontalGroup(
            pnlDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(pnlDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                        .addGroup(pnlDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                                .addComponent(jlbSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpwSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlbComando))
                            .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                                .addComponent(jlbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                        .addComponent(jbtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlDadosLoginLayout.setVerticalGroup(
            pnlDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                .addComponent(jlbComando)
                .addGroup(pnlDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(pnlDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pnlDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpwSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jbtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosLoginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlDadosLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDadosLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoginActionPerformed
       int count = 0;
       
       
        
        if (jtxCPF.getText().equals("") || jpwSenha.getText().equals("")) {
            //Preencha todos os campos
            JOptionPane.showMessageDialog(null, "Preencha todos os campos disponíveis para continuar!", "Aviso!", JOptionPane.WARNING_MESSAGE);
        } else if (jtxCPF.getText().equals("0") && jpwSenha.getText().equals("admin")) {
            new Principal().setVisible(true);
        } else {
            for (int i = 0; i < bd.getFuncionarios().size(); i++) {
                
                if (bd.getFuncionarios().get(i).getSenha().equals(jpwSenha.getText()) && bd.getFuncionarios().get(i).getCpf().equals(jtxCPF.getText())) {
                    if (bd.getFuncionarios().get(i) instanceof Ator) {
                        new VisualizarAtor((Ator) bd.getFuncionarios().get(i)).setVisible(true);
                        dispose();
                        break;

                    } else if (bd.getFuncionarios().get(i) instanceof Diretor) {
                        new VisualizarDiretor((Diretor) bd.getFuncionarios().get(i)).setVisible(true);
                        dispose();
                        break;
                    }
                }
                

            }
            
            

        }
    }//GEN-LAST:event_jbtLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtLogin;
    private javax.swing.JLabel jlbCPF;
    private javax.swing.JLabel jlbComando;
    private javax.swing.JLabel jlbSenha;
    private javax.swing.JPasswordField jpwSenha;
    private javax.swing.JTextField jtxCPF;
    private javax.swing.JPanel pnlDadosLogin;
    // End of variables declaration//GEN-END:variables
}
